services:
  - type: web
    name: upx-laravel
    plan: free
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:BOx58QfUHhhr0Cg1T1aVyWniwCTYyMEd7fm/ibxofeM=  # Substitua se necessário
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_DSN
        value: mongodb+srv://lucaspaifer:2212@cluster0.aeemvbu.mongodb.net/BoschDataBase?retryWrites=true&w=majority
      - key: APP_URL
        value: https://upx-laravel.onrender.com
      - key: APP_LOCALE
        value: pt-BR
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_ADDRESS
        value: noreply@bosch.com.br
      - key: MAIL_FROM_NAME
        value: Upx
