services:
  - type: web
    name: upx-laravel
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
        - .env.production
        - app/**
        - config/**
        - routes/**
        - public/**
        - composer.*
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:p+P+3+H3GZfQtBnHhy2TVBt+hSP2MEAuvpfOZPy6q1I=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://upx-laravel.onrender.com
      - key: DB_CONNECTION
        value: mongodb
      - key: DB_DATABASE
        value: BoschDataBase
      - key: MONGODB_URI
        value: mongodb://lucaspaifer:2212@cluster0-shard-00-00.aeemvbu.mongodb.net:27017,cluster0-shard-00-01.aeemvbu.mongodb.net:27017,cluster0-shard-00-02.aeemvbu.mongodb.net:27017/BoschDataBase?ssl=true&replicaSet=atlas-xxxx-shard-0&authSource=admin&retryWrites=true&w=majority
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_DRIVER
        value: file
